name: 'wap-action'

author: 'Tim Martin'

description: 'wap build and publish, https://github.com/t-mart/wap'

inputs:
  release-type:
    description: "Release type for publish. Can be none|alpha|beta|release"
    default: "alpha"
  curseforge-token:
    description: "Curseforge token to automate upload to Curseforge"
    default: "token-not-set"
  config-path:
    description: "The path to a custom configuration path. Defaults to `./wap.json`."
    default: "./wap.json"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: wap build
      shell: bash
      run: |
        uvx --from wow-addon-packager wap build --config-path "${{ inputs.config-path }}"

    - name: wap publish
      if: ${{ inputs.release-type != 'none' }}
      shell: bash
      run: |
        uvx --from wow-addon-packager wap publish --release-type "${{ inputs.release-type }}" --curseforge-token "${{ inputs.curseforge-token }}" --config-path "${{ inputs.config-path }}"
